# 
#  Copyright 2008
#  Texas Instruments Incorporated
#
#  All rights reserved.  Property of Texas Instruments Incorporated
#  Restricted rights to use, duplicate or disclose this code are
#  granted through contract.
# 
#

#
#  ======== makefile ========
#

all:
%::
	$(MAKE) -C evmDM6446 $@
	$(MAKE) -C evmDM6467 $@
#
#  @(#) ti.sdo.ce.examples.servers.video_copy; 1, 0, 0,130; 9-9-2008 02:04:23; /db/atree/library/trees/ce-h27x/src/
#

