#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = ti/sdo/ce/examples/codecs/viddec_copy
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/_gen.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/_gen.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/BuildEnvironment.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xmlgen.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xmlgen.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xdc.tci:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xdc.tci
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/IPackage.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/IPackage.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/ITarget.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/ITarget.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/package/gnu.targets.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/package/gnu.targets.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/PackageContents.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/PackageContents.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/recap.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/recap.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Library.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Library.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Executable.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Executable.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITarget.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITarget.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package/xdc.bld.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package/xdc.bld.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/spec/package/xdc.services.spec.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/spec/package/xdc.services.spec.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/ITarget.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/ITarget.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/om2.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/om2.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/package/ti.targets.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/package/ti.targets.sch
/opt/dvsdk_1_40_02_33/codec_engine_2_10_02/packages/config.bld:
package.mak: /opt/dvsdk_1_40_02_33/codec_engine_2_10_02/packages/config.bld
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Repository.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Repository.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/template.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/template.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/package/xdc.services.global.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/package/xdc.services.global.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Utils.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Utils.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/corevers/package/xdc.corevers.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/corevers/package/xdc.corevers.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Script.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Script.xs
package.mak: package.bld
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/Clock.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/Clock.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITargetFilter.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITargetFilter.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/include/utils.tci:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/include/utils.tci
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/shelf/package/xdc.shelf.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/shelf/package/xdc.shelf.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package/xdc.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package/xdc.sch
/opt/dvsdk_1_40_02_33/codec_engine_2_10_02/examples/user.bld:
package.mak: /opt/dvsdk_1_40_02_33/codec_engine_2_10_02/examples/user.bld
endif

ti.targets.C64P.rootDir ?= /opt/dvsdk_1_40_02_33/cg6x_6_0_16
ti.targets.packageBase ?= /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/
gnu.targets.MVArm9.rootDir ?= /opt/mv_pro_4.0.1/montavista/pro/devkit/arm/v5t_le
gnu.targets.packageBase ?= /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/
.PRECIOUS: $(XDCCFGDIR)/%.o64P
.PHONY: all,64P .dlls,64P .executables,64P test,64P
all,64P: .executables,64P
.executables,64P: .libraries,64P
.executables,64P: .dlls,64P
.dlls,64P: .libraries,64P
.libraries,64P: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,64P
	@$(ECHO) xdc .executables,64P
	@$(ECHO) xdc .libraries,64P
	@$(ECHO) xdc .dlls,64P

.PRECIOUS: $(XDCCFGDIR)/%.o470MV
.PHONY: all,470MV .dlls,470MV .executables,470MV test,470MV
all,470MV: .executables,470MV
.executables,470MV: .libraries,470MV
.executables,470MV: .dlls,470MV
.dlls,470MV: .libraries,470MV
.libraries,470MV: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,470MV
	@$(ECHO) xdc .executables,470MV
	@$(ECHO) xdc .libraries,470MV
	@$(ECHO) xdc .dlls,470MV


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.xml package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.xml package/%.xdc.inc package/%_ti.sdo.ce.examples.codecs.viddec_copy.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sdo.ce.examples.codecs.viddec_copy" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifneq (clean,$(MAKECMDGOALS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sdo.ce.examples.codecs.viddec_copy $@

ifneq (clean,$(MAKECMDGOALS))
package.mak:/opt/dvsdk_1_40_02_33/codec_engine_2_10_02/packages/ti/sdo/ce/utils/libvers.xdt
/opt/dvsdk_1_40_02_33/codec_engine_2_10_02/packages/ti/sdo/ce/utils/libvers.xdt:

endif
.libraries,64P .libraries: lib/viddec_copy.a64P

-include lib/viddec_copy.a64P.mak
lib/viddec_copy.a64P: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/viddec_copy/package/package_ti.sdo.ce.examples.codecs.viddec_copy.o64P package/lib/lib/viddec_copy/viddec_copy.o64P  into $@ ...
	$(ti.targets.C64P.rootDir)/bin/ar6x  rq $@   package/lib/lib/viddec_copy/package/package_ti.sdo.ce.examples.codecs.viddec_copy.o64P package/lib/lib/viddec_copy/viddec_copy.o64P 
lib/viddec_copy.a64P:C_DIR=
lib/viddec_copy.a64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

clean,64P clean::
	-$(RM) lib/viddec_copy.a64P
.libraries,470MV .libraries: lib/viddec_copy.a470MV

-include lib/viddec_copy.a470MV.mak
lib/viddec_copy.a470MV: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/viddec_copy/package/package_ti.sdo.ce.examples.codecs.viddec_copy.o470MV package/lib/lib/viddec_copy/viddec_copy.o470MV  into $@ ...
	$(gnu.targets.MVArm9.rootDir)/bin/arm_v5t_le-ar  cr $@   package/lib/lib/viddec_copy/package/package_ti.sdo.ce.examples.codecs.viddec_copy.o470MV package/lib/lib/viddec_copy/viddec_copy.o470MV 
lib/viddec_copy.a470MV:LD_LIBRARY_PATH=

clean,470MV clean::
	-$(RM) lib/viddec_copy.a470MV
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
viddec_copy.o64P,copy : package/lib/lib/viddec_copy/viddec_copy.o64P
package_ti.sdo.ce.examples.codecs.viddec_copy.s470MV,copy : package/lib/lib/viddec_copy/package/package_ti.sdo.ce.examples.codecs.viddec_copy.s470MV
viddec_copy.s64P,copy : package/lib/lib/viddec_copy/viddec_copy.s64P
package_ti.sdo.ce.examples.codecs.viddec_copy.o64P,copy : package/lib/lib/viddec_copy/package/package_ti.sdo.ce.examples.codecs.viddec_copy.o64P
viddec_copy.o470MV,copy : package/lib/lib/viddec_copy/viddec_copy.o470MV
package_ti.sdo.ce.examples.codecs.viddec_copy.s64P,copy : package/lib/lib/viddec_copy/package/package_ti.sdo.ce.examples.codecs.viddec_copy.s64P
viddec_copy.s470MV,copy : package/lib/lib/viddec_copy/viddec_copy.s470MV
package_ti.sdo.ce.examples.codecs.viddec_copy.o470MV,copy : package/lib/lib/viddec_copy/package/package_ti.sdo.ce.examples.codecs.viddec_copy.o470MV

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_TCOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sdo_ce_examples_codecs_viddec_copy
ti_sdo_ce_examples_codecs_viddec_copy.tar: package/package.xdc.xml
ti_sdo_ce_examples_codecs_viddec_copy.tar: package/package.cfg.xdc.inc
ti_sdo_ce_examples_codecs_viddec_copy.tar: package/package.xdc.inc
ti_sdo_ce_examples_codecs_viddec_copy.tar: lib/viddec_copy.a64P
ti_sdo_ce_examples_codecs_viddec_copy.tar: package/package.rel.dot
ti_sdo_ce_examples_codecs_viddec_copy.tar: package/package.bld.xml
ti_sdo_ce_examples_codecs_viddec_copy.tar: lib/viddec_copy.a470MV
ti_sdo_ce_examples_codecs_viddec_copy.tar: package/package.ext.xml
ti_sdo_ce_examples_codecs_viddec_copy.tar: package/build.cfg
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ti_sdo_ce_examples_codecs_viddec_copy.tar.dep
endif
package/rel/ti_sdo_ce_examples_codecs_viddec_copy/ti/sdo/ce/examples/codecs/viddec_copy/package/package.rel.xml:

ti_sdo_ce_examples_codecs_viddec_copy.tar: package/rel/ti_sdo_ce_examples_codecs_viddec_copy.xdc.inc package/rel/ti_sdo_ce_examples_codecs_viddec_copy/ti/sdo/ce/examples/codecs/viddec_copy/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKREL,package/rel/ti_sdo_ce_examples_codecs_viddec_copy.xdc.inc,package/rel/ti_sdo_ce_examples_codecs_viddec_copy.tar.dep)


release release,ti_sdo_ce_examples_codecs_viddec_copy: all ti_sdo_ce_examples_codecs_viddec_copy.tar
clean:: .clean
	-$(RM) ti_sdo_ce_examples_codecs_viddec_copy.tar
	-$(RM) package/rel/ti_sdo_ce_examples_codecs_viddec_copy.xdc.inc
	-$(RM) package/rel/ti_sdo_ce_examples_codecs_viddec_copy.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/viddec_copy))
    $(shell $(MKDIR) package/lib/lib/viddec_copy)
endif
ifeq (,$(wildcard package/lib/lib/viddec_copy/package))
    $(shell $(MKDIR) package/lib/lib/viddec_copy/package)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.sdo.ce.examples.codecs.viddec_copy.pjt
