#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = ti/sdo/ce/examples/extensions/scale
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/xdc.tci:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/xdc.tci
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/xmlgen.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/xmlgen.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/ti/targets/ITarget.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/ti/targets/ITarget.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/ti/targets/package.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/ti/targets/package.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/Executable.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/Executable.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/global/package/xdc.services.global.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/global/package/xdc.services.global.sch
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/_gen.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/_gen.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/package/xdc.bld.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/package/xdc.bld.sch
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/shelf/package/xdc.shelf.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/shelf/package/xdc.shelf.sch
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/spec/package/xdc.services.spec.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/spec/package/xdc.services.spec.sch
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/ITargetFilter.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/ITargetFilter.xs
/db/atree/library/trees/ce-h27x/src/codec_engine_2_10_02/examples/user.bld:
package.mak: /db/atree/library/trees/ce-h27x/src/codec_engine_2_10_02/examples/user.bld
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/PackageContents.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/PackageContents.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/Repository.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/Repository.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/IPackage.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/IPackage.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/include/utils.tci:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/include/utils.tci
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/corevers/package/xdc.corevers.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/corevers/package/xdc.corevers.sch
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/package.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/package.xs
package.mak: package.bld
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/Utils.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/Utils.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/recap.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/recap.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/gnu/targets/ITarget.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/gnu/targets/ITarget.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/package/xdc.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/package/xdc.sch
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/gnu/targets/package.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/gnu/targets/package.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/gnu/targets/package/gnu.targets.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/gnu/targets/package/gnu.targets.sch
/db/atree/library/trees/ce-h27x/src/codec_engine_2_10_02/packages/config.bld:
package.mak: /db/atree/library/trees/ce-h27x/src/codec_engine_2_10_02/packages/config.bld
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/template.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/template.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/om2.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/om2.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/global/Clock.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/services/global/Clock.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/ti/targets/package/ti.targets.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/ti/targets/package/ti.targets.sch
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/BuildEnvironment.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/Library.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/Library.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/ITarget.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/ITarget.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/package.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/package.xs
/db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/Script.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/xdc/bld/Script.xs
endif

ti.targets.C64P.rootDir ?= /db/toolsrc/library/tools/vendors/ti/c6x/6.0.16/Linux
ti.targets.packageBase ?= /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/ti/targets/
gnu.targets.MVArm9.rootDir ?= /db/toolsrc/library/tools/vendors/mvl/arm/mvl4.0-new/montavista/pro/devkit/arm/v5t_le
gnu.targets.packageBase ?= /db/rtree/install/trees/products/xdcprod-h24/product/Linux/xdc_3_00_06/packages/gnu/targets/
.PRECIOUS: $(XDCCFGDIR)/%.o64P
.PHONY: all,64P .dlls,64P .executables,64P test,64P
all,64P: .executables,64P
.executables,64P: .libraries,64P
.executables,64P: .dlls,64P
.dlls,64P: .libraries,64P
.libraries,64P: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,64P
	@$(ECHO) xdc .executables,64P
	@$(ECHO) xdc .libraries,64P
	@$(ECHO) xdc .dlls,64P

.PRECIOUS: $(XDCCFGDIR)/%.o470MV
.PHONY: all,470MV .dlls,470MV .executables,470MV test,470MV
all,470MV: .executables,470MV
.executables,470MV: .libraries,470MV
.executables,470MV: .dlls,470MV
.dlls,470MV: .libraries,470MV
.libraries,470MV: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,470MV
	@$(ECHO) xdc .executables,470MV
	@$(ECHO) xdc .libraries,470MV
	@$(ECHO) xdc .dlls,470MV


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.xml package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.xml package/%.xdc.inc package/%_ti.sdo.ce.examples.extensions.scale.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sdo.ce.examples.extensions.scale" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifneq (clean,$(MAKECMDGOALS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sdo.ce.examples.extensions.scale $@

ifneq (clean,$(MAKECMDGOALS))
package.mak:/db/atree/library/trees/ce-h27x/src/codec_engine_2_10_02/packages/ti/sdo/ce/utils/libvers.xdt
/db/atree/library/trees/ce-h27x/src/codec_engine_2_10_02/packages/ti/sdo/ce/utils/libvers.xdt:

endif
.libraries,470MV .libraries: lib/scale_debug.a470MV

-include lib/scale_debug.a470MV.mak
lib/scale_debug.a470MV: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/scale_debug/scale.o470MV package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.o470MV package/lib/lib/scale_debug/scale_skel.o470MV package/lib/lib/scale_debug/scale_stubs.o470MV  into $@ ...
	$(gnu.targets.MVArm9.rootDir)/bin/arm_v5t_le-ar  cr $@   package/lib/lib/scale_debug/scale.o470MV package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.o470MV package/lib/lib/scale_debug/scale_skel.o470MV package/lib/lib/scale_debug/scale_stubs.o470MV 
lib/scale_debug.a470MV:LD_LIBRARY_PATH=

clean,470MV clean::
	-$(RM) lib/scale_debug.a470MV
.libraries,64P .libraries: lib/scale_debug.a64P

-include lib/scale_debug.a64P.mak
lib/scale_debug.a64P: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/scale_debug/scale.o64P package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.o64P package/lib/lib/scale_debug/scale_skel.o64P package/lib/lib/scale_debug/scale_stubs.o64P  into $@ ...
	$(ti.targets.C64P.rootDir)/bin/ar6x  rq $@   package/lib/lib/scale_debug/scale.o64P package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.o64P package/lib/lib/scale_debug/scale_skel.o64P package/lib/lib/scale_debug/scale_stubs.o64P 
lib/scale_debug.a64P:C_DIR=
lib/scale_debug.a64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

clean,64P clean::
	-$(RM) lib/scale_debug.a64P
.libraries,64P .libraries: lib/scale.a64P

-include lib/scale.a64P.mak
lib/scale.a64P: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/scale/scale.o64P package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.o64P package/lib/lib/scale/scale_skel.o64P package/lib/lib/scale/scale_stubs.o64P  into $@ ...
	$(ti.targets.C64P.rootDir)/bin/ar6x  rq $@   package/lib/lib/scale/scale.o64P package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.o64P package/lib/lib/scale/scale_skel.o64P package/lib/lib/scale/scale_stubs.o64P 
lib/scale.a64P:C_DIR=
lib/scale.a64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)

clean,64P clean::
	-$(RM) lib/scale.a64P
.libraries,470MV .libraries: lib/scale.a470MV

-include lib/scale.a470MV.mak
lib/scale.a470MV: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/scale/scale.o470MV package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.o470MV package/lib/lib/scale/scale_skel.o470MV package/lib/lib/scale/scale_stubs.o470MV  into $@ ...
	$(gnu.targets.MVArm9.rootDir)/bin/arm_v5t_le-ar  cr $@   package/lib/lib/scale/scale.o470MV package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.o470MV package/lib/lib/scale/scale_skel.o470MV package/lib/lib/scale/scale_stubs.o470MV 
lib/scale.a470MV:LD_LIBRARY_PATH=

clean,470MV clean::
	-$(RM) lib/scale.a470MV
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.sdo.ce.examples.extensions.scale.o470MV,copy
package_ti.sdo.ce.examples.extensions.scale.o470MV,copy : package_ti.sdo.ce.examples.extensions.scale.o470MV,0,copy package_ti.sdo.ce.examples.extensions.scale.o470MV,1,copy 
	@

package_ti.sdo.ce.examples.extensions.scale.o470MV,0,copy : package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.o470MV
package_ti.sdo.ce.examples.extensions.scale.o470MV,1,copy : package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.o470MV
.PHONY: scale_stubs.s470MV,copy
scale_stubs.s470MV,copy : scale_stubs.s470MV,0,copy scale_stubs.s470MV,1,copy 
	@

scale_stubs.s470MV,0,copy : package/lib/lib/scale/scale_stubs.s470MV
scale_stubs.s470MV,1,copy : package/lib/lib/scale_debug/scale_stubs.s470MV
.PHONY: scale.s470MV,copy
scale.s470MV,copy : scale.s470MV,0,copy scale.s470MV,1,copy 
	@

scale.s470MV,0,copy : package/lib/lib/scale/scale.s470MV
scale.s470MV,1,copy : package/lib/lib/scale_debug/scale.s470MV
.PHONY: package_ti.sdo.ce.examples.extensions.scale.o64P,copy
package_ti.sdo.ce.examples.extensions.scale.o64P,copy : package_ti.sdo.ce.examples.extensions.scale.o64P,0,copy package_ti.sdo.ce.examples.extensions.scale.o64P,1,copy 
	@

package_ti.sdo.ce.examples.extensions.scale.o64P,0,copy : package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.o64P
package_ti.sdo.ce.examples.extensions.scale.o64P,1,copy : package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.o64P
.PHONY: scale_stubs.o64P,copy
scale_stubs.o64P,copy : scale_stubs.o64P,0,copy scale_stubs.o64P,1,copy 
	@

scale_stubs.o64P,0,copy : package/lib/lib/scale/scale_stubs.o64P
scale_stubs.o64P,1,copy : package/lib/lib/scale_debug/scale_stubs.o64P
.PHONY: package_ti.sdo.ce.examples.extensions.scale.s64P,copy
package_ti.sdo.ce.examples.extensions.scale.s64P,copy : package_ti.sdo.ce.examples.extensions.scale.s64P,0,copy package_ti.sdo.ce.examples.extensions.scale.s64P,1,copy 
	@

package_ti.sdo.ce.examples.extensions.scale.s64P,0,copy : package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.s64P
package_ti.sdo.ce.examples.extensions.scale.s64P,1,copy : package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.s64P
.PHONY: scale_stubs.o470MV,copy
scale_stubs.o470MV,copy : scale_stubs.o470MV,0,copy scale_stubs.o470MV,1,copy 
	@

scale_stubs.o470MV,0,copy : package/lib/lib/scale/scale_stubs.o470MV
scale_stubs.o470MV,1,copy : package/lib/lib/scale_debug/scale_stubs.o470MV
.PHONY: scale_stubs.s64P,copy
scale_stubs.s64P,copy : scale_stubs.s64P,0,copy scale_stubs.s64P,1,copy 
	@

scale_stubs.s64P,0,copy : package/lib/lib/scale/scale_stubs.s64P
scale_stubs.s64P,1,copy : package/lib/lib/scale_debug/scale_stubs.s64P
.PHONY: scale_skel.s470MV,copy
scale_skel.s470MV,copy : scale_skel.s470MV,0,copy scale_skel.s470MV,1,copy 
	@

scale_skel.s470MV,0,copy : package/lib/lib/scale/scale_skel.s470MV
scale_skel.s470MV,1,copy : package/lib/lib/scale_debug/scale_skel.s470MV
.PHONY: scale.o64P,copy
scale.o64P,copy : scale.o64P,0,copy scale.o64P,1,copy 
	@

scale.o64P,0,copy : package/lib/lib/scale/scale.o64P
scale.o64P,1,copy : package/lib/lib/scale_debug/scale.o64P
.PHONY: scale.s64P,copy
scale.s64P,copy : scale.s64P,0,copy scale.s64P,1,copy 
	@

scale.s64P,0,copy : package/lib/lib/scale/scale.s64P
scale.s64P,1,copy : package/lib/lib/scale_debug/scale.s64P
.PHONY: scale.o470MV,copy
scale.o470MV,copy : scale.o470MV,0,copy scale.o470MV,1,copy 
	@

scale.o470MV,0,copy : package/lib/lib/scale/scale.o470MV
scale.o470MV,1,copy : package/lib/lib/scale_debug/scale.o470MV
.PHONY: package_ti.sdo.ce.examples.extensions.scale.s470MV,copy
package_ti.sdo.ce.examples.extensions.scale.s470MV,copy : package_ti.sdo.ce.examples.extensions.scale.s470MV,0,copy package_ti.sdo.ce.examples.extensions.scale.s470MV,1,copy 
	@

package_ti.sdo.ce.examples.extensions.scale.s470MV,0,copy : package/lib/lib/scale/package/package_ti.sdo.ce.examples.extensions.scale.s470MV
package_ti.sdo.ce.examples.extensions.scale.s470MV,1,copy : package/lib/lib/scale_debug/package/package_ti.sdo.ce.examples.extensions.scale.s470MV
.PHONY: scale_skel.o64P,copy
scale_skel.o64P,copy : scale_skel.o64P,0,copy scale_skel.o64P,1,copy 
	@

scale_skel.o64P,0,copy : package/lib/lib/scale/scale_skel.o64P
scale_skel.o64P,1,copy : package/lib/lib/scale_debug/scale_skel.o64P
.PHONY: scale_skel.o470MV,copy
scale_skel.o470MV,copy : scale_skel.o470MV,0,copy scale_skel.o470MV,1,copy 
	@

scale_skel.o470MV,0,copy : package/lib/lib/scale/scale_skel.o470MV
scale_skel.o470MV,1,copy : package/lib/lib/scale_debug/scale_skel.o470MV
.PHONY: scale_skel.s64P,copy
scale_skel.s64P,copy : scale_skel.s64P,0,copy scale_skel.s64P,1,copy 
	@

scale_skel.s64P,0,copy : package/lib/lib/scale/scale_skel.s64P
scale_skel.s64P,1,copy : package/lib/lib/scale_debug/scale_skel.s64P

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_TCOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sdo_ce_examples_extensions_scale
ti_sdo_ce_examples_extensions_scale.tar: lib/scale_debug.a470MV
ti_sdo_ce_examples_extensions_scale.tar: package/package.xdc.xml
ti_sdo_ce_examples_extensions_scale.tar: lib/scale.a64P
ti_sdo_ce_examples_extensions_scale.tar: package/package.cfg.xdc.inc
ti_sdo_ce_examples_extensions_scale.tar: package/package.xdc.inc
ti_sdo_ce_examples_extensions_scale.tar: package/package.rel.dot
ti_sdo_ce_examples_extensions_scale.tar: lib/scale.a470MV
ti_sdo_ce_examples_extensions_scale.tar: scale.h
ti_sdo_ce_examples_extensions_scale.tar: package/package.bld.xml
ti_sdo_ce_examples_extensions_scale.tar: lib/scale_debug.a64P
ti_sdo_ce_examples_extensions_scale.tar: package/package.ext.xml
ti_sdo_ce_examples_extensions_scale.tar: package/build.cfg
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ti_sdo_ce_examples_extensions_scale.tar.dep
endif
package/rel/ti_sdo_ce_examples_extensions_scale/ti/sdo/ce/examples/extensions/scale/package/package.rel.xml:

ti_sdo_ce_examples_extensions_scale.tar: package/rel/ti_sdo_ce_examples_extensions_scale.xdc.inc package/rel/ti_sdo_ce_examples_extensions_scale/ti/sdo/ce/examples/extensions/scale/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKREL,package/rel/ti_sdo_ce_examples_extensions_scale.xdc.inc,package/rel/ti_sdo_ce_examples_extensions_scale.tar.dep)


release release,ti_sdo_ce_examples_extensions_scale: all ti_sdo_ce_examples_extensions_scale.tar
clean:: .clean
	-$(RM) ti_sdo_ce_examples_extensions_scale.tar
	-$(RM) package/rel/ti_sdo_ce_examples_extensions_scale.xdc.inc
	-$(RM) package/rel/ti_sdo_ce_examples_extensions_scale.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/scale_debug))
    $(shell $(MKDIR) package/lib/lib/scale_debug)
endif
ifeq (,$(wildcard package/lib/lib/scale))
    $(shell $(MKDIR) package/lib/lib/scale)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib/lib/scale/package))
    $(shell $(MKDIR) package/lib/lib/scale/package)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/lib/lib/scale_debug/package))
    $(shell $(MKDIR) package/lib/lib/scale_debug/package)
endif
endif
clean::
	-$(RMDIR) package


clean:: 
	-$(RM) package/ti.sdo.ce.examples.extensions.scale.pjt
