# 
#  Copyright 2008
#  Texas Instruments Incorporated
#
#  All rights reserved.  Property of Texas Instruments Incorporated
#  Restricted rights to use, duplicate or disclose this code are
#  granted through contract.
# 
#

#
#  ======== makefile ========
#

all:
%::
	$(MAKE) -C video_copy $@
	$(MAKE) -C all_codecs $@
#
#  @(#) ti.sdo.ce.examples.servers; 1,0,0,131; 9-9-2008 02:04:11; /db/atree/library/trees/ce-h27x/src/
#

