#ifndef ti_sdo_ce_examples_apps_server_api_example_audio_server__
#define ti_sdo_ce_examples_apps_server_api_example_audio_server__

#endif /* ti_sdo_ce_examples_apps_server_api_example_audio_server__ */ 
