#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = ceapp
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/_gen.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/_gen.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/BuildEnvironment.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xmlgen.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xmlgen.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/File.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/File.xs
package.mak: package.bld
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xdc.tci:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xdc.tci
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/IPackage.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/IPackage.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/package/gnu.targets.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/package/gnu.targets.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/PackageContents.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/PackageContents.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/recap.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/recap.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Library.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Library.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Executable.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Executable.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITarget.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITarget.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package/xdc.bld.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package/xdc.bld.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/spec/package/xdc.services.spec.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/spec/package/xdc.services.spec.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/ITarget.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/ITarget.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/om2.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/om2.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/package/xdc.services.io.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/package/xdc.services.io.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Repository.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Repository.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/template.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/template.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/package/xdc.services.global.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/package/xdc.services.global.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/package.xs.xdt
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Utils.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Utils.xs
package.mak: config.bld
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/corevers/package/xdc.corevers.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/corevers/package/xdc.corevers.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Script.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Script.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/Clock.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/Clock.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITargetFilter.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITargetFilter.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/compiler.opt.xdt
/opt/dvsdk_1_40_02_33/xdc_3_00_06/include/utils.tci:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/include/utils.tci
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/shelf/package/xdc.shelf.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/shelf/package/xdc.shelf.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package/xdc.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package/xdc.sch
endif

gnu.targets.MVArm9.rootDir ?= /opt/mv_pro_4.0.1/montavista/pro/devkit/arm/v5t_le
gnu.targets.packageBase ?= /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/gnu/targets/
.PRECIOUS: $(XDCCFGDIR)/%.o470MV
.PHONY: all,470MV .dlls,470MV .executables,470MV test,470MV
all,470MV: .executables,470MV
.executables,470MV: .libraries,470MV
.executables,470MV: .dlls,470MV
.dlls,470MV: .libraries,470MV
.libraries,470MV: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,470MV
	@$(ECHO) xdc .executables,470MV
	@$(ECHO) xdc .libraries,470MV
	@$(ECHO) xdc .dlls,470MV


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.xml package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.xml package/%.xdc.inc package/%_ceapp.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ceapp" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.executables,470MV .executables: ceapp.x470MV

-include package/cfg/ceapp_x470MV.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/ceapp_x470MV.dep
endif
package/cfg/ceapp_x470MV.o470MV : | package/cfg/ceapp_x470MV.xdl
ceapp.x470MV:
	$(RM) $@
	@$(MSG) lnk470MV $@ ...
	$(gnu.targets.MVArm9.rootDir)/bin/arm_v5t_le-gcc    -o $@ package/cfg/ceapp_x470MV.o470MV  package/cfg/ceapp_x470MV.xdl  -lstdc++ -L$(gnu.targets.MVArm9.rootDir)/armv5tl-montavista-linuxeabi/lib
	
ceapp.x470MV:LD_LIBRARY_PATH=


ifeq (,$(wildcard .libraries,470MV))
ceapp.x470MV package/cfg/ceapp_x470MV.c: .libraries,470MV
endif

package/cfg/ceapp_x470MV.c package/cfg/ceapp_x470MV.h package/cfg/ceapp_x470MV.xdl: override _PROG_NAME := ceapp.x470MV
package/cfg/ceapp_x470MV.c: package/cfg/ceapp_x470MV.cfg
ceapp.test test,470MV test: ceapp.x470MV.test

ceapp.x470MV.test:: ceapp.x470MV
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 ceapp.x470MV.test
else
	@$(MSG) running $<  ...
	$(call EXEC.ceapp.x470MV, ) 
endif


clean:: clean,470MV
	-$(RM) package/cfg/ceapp_x470MV.cfg
	-$(RM) package/cfg/ceapp_x470MV.dep
	-$(RM) package/cfg/ceapp_x470MV.c
	-$(RM) package/cfg/ceapp_x470MV.xdc.inc

clean,470MV::
	-$(RM) ceapp.x470MV
	-$(RM) .tmp,ceapp.x470MV,*

%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
ceapp_x470MV.o470MV,copy : package/cfg/ceapp_x470MV.o470MV
ceapp_x470MV.s470MV,copy : package/cfg/ceapp_x470MV.s470MV

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_TCOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ceapp
ceapp.tar: package/package.xdc.xml
ceapp.tar: package/build.cfg
ceapp.tar: package/package.ext.xml
ceapp.tar: package/package.xdc.inc
ceapp.tar: package/package.bld.xml
ceapp.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ceapp.tar.dep
endif
package/rel/ceapp/ceapp/package/package.rel.xml:

ceapp.tar: package/rel/ceapp.xdc.inc package/rel/ceapp/ceapp/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKREL,package/rel/ceapp.xdc.inc,package/rel/ceapp.tar.dep)


release release,ceapp: all ceapp.tar
clean:: .clean
	-$(RM) ceapp.tar
	-$(RM) package/rel/ceapp.xdc.inc
	-$(RM) package/rel/ceapp.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
