#
#  Copyright 2008 by Texas Instruments Incorporated.
#  
#  All rights reserved. Property of Texas Instruments Incorporated.
#  Restricted rights to use, duplicate or disclose this code are
#  granted through contract.
#  
#

#
#  ======== makefile ========
#  GNUmake-based makefile.
#

# include the files that defines XDC package, paths and build rules
EXAMPLES_ROOTDIR := $(CURDIR)/../../../../../..

include $(EXAMPLES_ROOTDIR)/xdcpaths.mak

# [CE] add the examples directory itself to the list of paths to packages
XDC_PATH := $(EXAMPLES_ROOTDIR);$(XDC_PATH)

include $(EXAMPLES_ROOTDIR)/buildutils/xdcrules.mak
#
#  @(#) ti.sdo.ce.examples.codecs.imgenc1_copy; 1,0,0,131; 9-9-2008 02:02:56; /db/atree/library/trees/ce-h27x/src/
#

