#ifndef ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll__
#define ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll__

#endif /* ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll__ */ 
