#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = video_copy
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCPKGS = $(call pkgsearch,ti/bios/include )
XDCINCS += $(if $(XDCPKGS),-I$(subst $(space), -I,$(XDCPKGS)))
IMPORTPATH += $(if $(XDCPKGS),;$(subst $(space),;,$(XDCPKGS)))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/_gen.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/_gen.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/BuildEnvironment.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xmlgen.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xmlgen.xs
package.mak: config.bld
package.mak: package.bld
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/File.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/File.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xdc.tci:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/xdc.tci
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/IPackage.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/IPackage.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/ITarget.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/ITarget.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/PackageContents.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/PackageContents.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/recap.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/recap.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Library.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Library.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Executable.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Executable.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITarget.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITarget.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package/xdc.bld.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/package/xdc.bld.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/spec/package/xdc.services.spec.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/spec/package/xdc.services.spec.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/om2.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/om2.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/package/ti.targets.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/package/ti.targets.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/package/xdc.services.io.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/io/package/xdc.services.io.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Repository.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Repository.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/template.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/template.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/package/xdc.services.global.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/package/xdc.services.global.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/package.xs.xdt
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Utils.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Utils.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/corevers/package/xdc.corevers.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/corevers/package/xdc.corevers.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Script.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/Script.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/Clock.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/services/global/Clock.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITargetFilter.xs:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/bld/ITargetFilter.xs
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/tools/configuro/template/compiler.opt.xdt
/opt/dvsdk_1_40_02_33/xdc_3_00_06/include/utils.tci:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/include/utils.tci
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/shelf/package/xdc.shelf.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/shelf/package/xdc.shelf.sch
/opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package/xdc.sch:
package.mak: /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/xdc/package/xdc.sch
endif

ti.targets.C64P.rootDir ?= /opt/dvsdk_1_40_02_33/cg6x_6_0_16
ti.targets.packageBase ?= /opt/dvsdk_1_40_02_33/xdc_3_00_06/packages/ti/targets/
.PRECIOUS: $(XDCCFGDIR)/%.o64P
.PHONY: all,64P .dlls,64P .executables,64P test,64P
all,64P: .executables,64P
.executables,64P: .libraries,64P
.executables,64P: .dlls,64P
.dlls,64P: .libraries,64P
.libraries,64P: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,64P
	@$(ECHO) xdc .executables,64P
	@$(ECHO) xdc .libraries,64P
	@$(ECHO) xdc .dlls,64P


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.xml package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.xml package/%.xdc.inc package/%_video_copy.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package video_copy" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.executables,64P .executables: video_copy.x64P

package/cfg/video_copy_x64Pcfg_c.c package/cfg/video_copy_x64Pcfg.s62 package/cfg/video_copy_x64Pcfg.cmd: override _PROG_NAME := video_copy.x64P
-include package/cfg/video_copy_x64P.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/video_copy_x64P.dep
endif
package/cfg/video_copy_x64P.o64P package/cfg/video_copy_x64Pcfg_c.o64P package/cfg/video_copy_x64Pcfg.o64P : | package/cfg/video_copy_x64P.xdl
video_copy.x64P: package/cfg/video_copy_x64Pcfg.cmd
video_copy.x64P:
	$(RM) $@
	@$(MSG) lnk64P $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.C64P.rootDir)/bin/lnk6x -w -q -u _c_int00  -q -o $@ package/cfg/video_copy_x64P.o64P package/cfg/video_copy_x64Pcfg_c.o64P package/cfg/video_copy_x64Pcfg.o64P  package/cfg/video_copy_x64P.xdl  -c -m $(XDCCFGDIR)/$@.map -l $(ti.targets.C64P.rootDir)/lib/rts64plus.lib
	
video_copy.x64P:C_DIR=
video_copy.x64P: PATH:=$(ti.targets.C64P.rootDir)/bin/:$(PATH)


ifeq (,$(wildcard .libraries,64P))
video_copy.x64P package/cfg/video_copy_x64P.c: .libraries,64P
endif

package/cfg/video_copy_x64P.c package/cfg/video_copy_x64P.h package/cfg/video_copy_x64P.xdl: override _PROG_NAME := video_copy.x64P
package/cfg/video_copy_x64P.c: package/cfg/video_copy_x64P.cfg
video_copy.test test,64P test: video_copy.x64P.test

video_copy.x64P.test:: video_copy.x64P
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 video_copy.x64P.test
else
	@$(MSG) running $<  ...
	$(call EXEC.video_copy.x64P, ) 
endif


clean:: clean,64P
	-$(RM) package/cfg/video_copy_x64P.cfg
	-$(RM) package/cfg/video_copy_x64P.dep
	-$(RM) package/cfg/video_copy_x64P.c
	-$(RM) package/cfg/video_copy_x64P.xdc.inc

clean,64P::
	-$(RM) video_copy.x64P
	-$(RM) .tmp,video_copy.x64P,*

clean:: 
	-$(RM) package/cfg/video_copy_x64P.pjt
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
video_copy_x64Pcfg_c.o64P,copy : package/cfg/video_copy_x64Pcfg_c.o64P
video_copy_x64Pcfg_c.s64P,copy : package/cfg/video_copy_x64Pcfg_c.s64P
video_copy_x64Pcfg.o64P,copy : package/cfg/video_copy_x64Pcfg.o64P
video_copy_x64P.o64P,copy : package/cfg/video_copy_x64P.o64P
video_copy_x64P.s64P,copy : package/cfg/video_copy_x64P.s64P

$(XDCCFGDIR)%cfg.s62 $(XDCCFGDIR)%cfg_c.c $(XDCCFGDIR)%cfg.cmd $(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_TCOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,video_copy
video_copy.tar: package/package.xdc.xml
video_copy.tar: package/build.cfg
video_copy.tar: package/package.ext.xml
video_copy.tar: package/package.xdc.inc
video_copy.tar: package/package.bld.xml
video_copy.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/video_copy.tar.dep
endif
package/rel/video_copy/video_copy/package/package.rel.xml:

video_copy.tar: package/rel/video_copy.xdc.inc package/rel/video_copy/video_copy/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKREL,package/rel/video_copy.xdc.inc,package/rel/video_copy.tar.dep)


release release,video_copy: all video_copy.tar
clean:: .clean
	-$(RM) video_copy.tar
	-$(RM) package/rel/video_copy.xdc.inc
	-$(RM) package/rel/video_copy.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
clean:: 
	-$(RM) package/video_copy.pjt
