#ifndef ti_sdo_ce_examples_apps_audio1_ires_audio1_ires_server__
#define ti_sdo_ce_examples_apps_audio1_ires_audio1_ires_server__

#endif /* ti_sdo_ce_examples_apps_audio1_ires_audio1_ires_server__ */ 
