#
#  Copyright 2008 by Texas Instruments Incorporated.
#  
#  All rights reserved. Property of Texas Instruments Incorporated.
#  Restricted rights to use, duplicate or disclose this code are
#  granted through contract.
#  
#

all:
%::
	$(MAKE) -C scale $@
#
#  @(#) ti.sdo.ce.examples.extensions; 1,0,0,131; 9-9-2008 02:04:00; /db/atree/library/trees/ce-h27x/src/
#

