#ifndef ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig__
#define ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig__

#endif /* ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig__ */ 
