# 
#  Copyright 2008
#  Texas Instruments Incorporated
#
#  All rights reserved.  Property of Texas Instruments Incorporated
#  Restricted rights to use, duplicate or disclose this code are
#  granted through contract.
# 
#

#
#  ======== makefile ========
#

all:
%::
	$(MAKE) -C viddec1_copy $@
	$(MAKE) -C viddec2_copy $@
	$(MAKE) -C videnc1_copy $@
	$(MAKE) -C imgdec1_copy $@
	$(MAKE) -C imgenc1_copy $@
	$(MAKE) -C sphenc1_copy $@
	$(MAKE) -C sphdec1_copy $@
	$(MAKE) -C audenc1_copy $@
	$(MAKE) -C auddec1_copy $@
	$(MAKE) -C viddec_copy $@
	$(MAKE) -C videnc_copy $@
	$(MAKE) -C imgdec_copy $@
	$(MAKE) -C imgenc_copy $@
	$(MAKE) -C auddec_copy $@
	$(MAKE) -C audenc_copy $@
	$(MAKE) -C sphenc_copy $@
	$(MAKE) -C sphdec_copy $@
	$(MAKE) -C scale $@
	$(MAKE) -C g711 $@
	$(MAKE) -C vidtranscode_copy $@
	$(MAKE) -C vidanalytics_copy $@
#
#  @(#) ti.sdo.ce.examples.codecs; 1,0,0,132; 9-9-2008 02:02:20; /db/atree/library/trees/ce-h27x/src/
#

